services:
  - name: hackrx-qa-system
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=$PORT --timeout-keep-alive 300 --workers 1
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.7
